### ISSUE TITLE
Fundamental problem with OKE-Challenge

### ISSUE THREAD

**Issue by csarven** [anuzzolese/oke-challenge#12]
It is a lost cause when the submission format should be in LNCS (and presumably in PDF) when the challenge is about "knowledge" "extraction". What do you expect to do next year? A challenge to extract knowledge out of this year's OKE-Challenge PDFs? :+1:

**Comment by rtroncy** [comment]
The outcome of this challenge is not a paper describing a system but the actual system you can run in order to reproduce results that are reported in the paper. Do you see the difference?

**Comment by csarven** [comment]
What I see is what's left behind for the future. Do you see the difference?

If the paper is irrelevant, why ask for it? A pastebin, an email, a tweet, a URL to the work will do.

**Comment by rtroncy** [comment]
It's hard to explain what a system does in a tweet. Have you try?
The system URL is, however, required to participate. This is what is left for the future.
