### ISSUE TITLE
Boundary issue for the instance http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-15#char=2,27

### ISSUE THREAD

**Issue by giusepperizzo** [anuzzolese/oke-challenge#16]
Hello,

http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-15#char=2,27
-> 
http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-15#char=2,28

and therefore

 nif:anchorOf          "native of Auburn, New Yor"@en
->
 nif:anchorOf          "native of Auburn, New York"@en

Am I mistaken?

**Comment by anuzzolese** [comment]
Hi Giuseppe,

you are right, the URI and the label are incorrect, while nif:beginIndex and nif:endIndex are correct.
I am going to fix the issue.

Andrea

**Comment by der-bruemmer** [comment]
You are correct. The URI should be 
http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-15#char=2,28 to correspond with the nif:endIndex

Checking the dataset, two further errors come up:

http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-90#char=177,188
 nif:anchorOf "Charborough House"; 
 itsrdf:taIdentRef     oke:Charborough_House .

is wrong. It should be 

http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-90#char=177,188
 nif:anchorOf "Charborough"; 
 itsrdf:taIdentRef     oke:Charborough .

In the same vein,

http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-90#char=42,53
nif:anchorOf          "Charborough"@en ;
itsrdf:taIdentRef     oke:Charborough .

should be 

http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-90#char=42,59
 nif:anchorOf          "Charborough House"@en ;
 nif:beginIndex        "42"^^xsd:int ;
 nif:endIndex          "59"^^xsd:int ;
 itsrdf:taIdentRef     oke:Charborough_House .

Have the datasets been validated? Shall I take a look at the other one?

**Comment by giusepperizzo** [comment]
tnx
