### ISSUE TITLE
Possible linked entity error in task-1 training set

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#18]
Hi,

Is this instance correct ?

```
oke:Andrea_Pole  a  dul:Person , owl:Individual ;
        rdfs:label  "Thomas Pole"@en ;
        owl:sameAs  dbpedia:Thomas_Pole .
```

Because in the Thomas Pole wikipedia page, nowhere they mention the name "Andrea Pole". Unless "Andrea Pole" and "Thomas Pole" are the same person ?

Cheers.

**Comment by anuzzolese** [comment]
The resolution to DBpedia in not correct.
Hence, only 

oke:Andrea_Pole  a  dul:Person , owl:Individual ;
        rdfs:label  "Thomas Pole"@en .

is valid.

**Comment by jplu** [comment]
Hi, I'm still seeing:

```
oke:Thomas_Pole  a  dul:Person , owl:Individual ;
        rdfs:label  "Thomas Pole"@en ;
        owl:sameAs  dbpedia:Thomas_Pole .
```

In the last commit.

**Comment by rtroncy** [comment]
@anuzzolese Please, indicate the commit link that shows the change done.
