### ISSUE TITLE
Empty sentence is task-1 training set

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#3]
Hi,

In analysing the task-1 training set I saw that one of the sentences is an empty string. Then I was asking me if it is an error or not ?

The sentence has the URI: `<http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/sentence-67#char=0,0>`

If it is normal I'm curious to know why adding an empty sentence.

cc @giusepperizzo and @rtroncy

**Comment by AnLiGentile** [comment]
hi Julien,
looks like a mistake to me, Andrea should confirm that.
I'll delete it.
tnx
Annalisa

**Comment by anuzzolese** [comment]
Such an individual has been removed.
