### ISSUE TITLE
Small typo in task-1 training set

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#4]
Hi,

There is a small typo in the dataset. The `nif:String` described by `oke:sentence-95#char=48,55` that represents the mention `country` is linked to `oke:County_2`, should be `oke:Country_2` instead.

cc @rtroncy and @giusepperizzo

Regards.

**Comment by anuzzolese** [comment]
Thanks Julien!

## Fixed.

Andrea
