### ISSUE TITLE
Typo in sentence-9 task-1 training set

### ISSUE THREAD

**Issue by jplu** [anuzzolese/oke-challenge#5]
Hi,

I saw another typo. In `oke:sentence-9#char=37,42` the associated entity is `oke:judge`, should be `oke:Judge` instead.

cc @rtroncy and @giusepperizzo

Cheers

**Comment by anuzzolese** [comment]
oke:judge is a valid URI even if another oke:Judge already exists.
The way you generate URIs is not evaluated.
What is really relevant is the NIF annotation and eventually the linking to DBpedia.

## 

Andrea

**Comment by jplu** [comment]
Ok so I'm curious to know why mixing things, to describe a "judge" there is 3 different resources:

```
oke:Judge  a        dul:Role , owl:Individual ;
        rdfs:label  "Judge"@en ;
        owl:sameAs dbpedia:Judge .
```

```
oke:judge  a        dul:Role , owl:Individual ;
        rdfs:label  "judge"@en ;
        owl:sameAs  dbpedia:United_States_federal_judge .
```

```
oke:Federal_Judge  a        dul:Role , owl:Individual ;
        rdfs:label  "Judge"@en ;
        owl:sameAs  dbpedia:United_States_federal_judge .
```

It is complicated to understand why these differences.

**Comment by anuzzolese** [comment]
It not so much complicated.
In fact, we first identified discourse referents in the corpus manually by providing new URIs and then we linked them to DBpedia entities, it is possible to have different newly generated URIs for a same discourse referent.
Nevertheless, the entity reconciliation problem is solved by means of entity linking.

You can have different “internal” URIs (those with prefix oke:). 
Thus, semantically it is pretty simple and correct: 
in case you have owl:sameAs axioms you can use their semantic closure to infer those entities are the same (e.g., oke:judge and oke:Federal_Judge);
in case you do not have owl:sameAs axioms you cannot state anything, hence it is better to keep things distinct.

It is important to remark that URIs are not evaluated, but their associated text context and owl:sameAs are.

I hope it helps,
Andrea

**Comment by jplu** [comment]
Ok, it is clearer now!

Thank you very much for this explanation.
